### PR TITLE
Bugfix: enabled modules are not listed properly in the StatefulSet

### PR DESCRIPTION
**Pull request by zoltan-fedor**
The StatefulSet is not listing the enabled modules properly.
Also due to Helm 2 support the _helpers was quite a bit of spaghetti code which would become unmanagable as mode modules become available.

As Helm 2 support has been dropped, I could rework this to be a lot cleaner in Helm 3.

### CODE REVIEW

**Comment by zoltan-fedor** [comment]
I agree with the CLA.

**Comment by etiennedi** [comment]
The test was red on CI:
```
Test if 'value: text2vec-transformers,qna-transformers,img2vec-neural,ner-transformers,text-spellcheck' exists using: '--set modules.text2vec-contextionary.enabled=false --set modules.text2vec-transformers.enabled=true --set modules.img2vec-neural.enabled=true --set modules.qna-transformers.enabled=true --set modules.text-spellcheck.enabled=true --set modules.ner-transformers.enabled=true' settings
error: 'value: text2vec-transformers,qna-transformers,img2vec-neural,ner-transformers,text-spellcheck' was not found
```

could it be that the test somehow assumed a specific order that is no longer guaranteed? Does it maybe also require udpating? (cc @antas-marcin)

**Comment by zoltan-fedor** [comment]
> 

Yes, I am sure that it is the order - see screen below.
Do you want to me swap the order of text-spellcheck and ner-transformers?

image

**Comment by etiennedi** [comment]
Either that or change the expected order in the test. Unless you want to rework the test to be independent of any order ;-)

**Comment by zoltan-fedor** [comment]
> Either that or change the expected order in the test. Unless you want to rework the test to be independent of any order ;-)
> 
> EDIT: Haha, you already pushed something while I was typing. Thanks!

Hah, we changed at the same time, so it fails again! :-)
I think I will leave it to you now, so we don't do it again at the same time. Could you please change the test back, so it matches the order of the modules we have now? Thanks

**Comment by etiennedi** [comment]
I didn't make any changes - I just pushed something to a different branch and prior to that I fixed the merge conflict with master :-)

**Comment by zoltan-fedor** [comment]
> 

Okey, then would you want me to change the order of modules in the code back, so it matches what order the test expect? I just don't want to end up doing it the same time again while you swap the order in the test, so we end up in conflict again. :-)

**Comment by etiennedi** [comment]
Yes, please. I'm not touching this PR until it's green :-)

**Comment by zoltan-fedor** [comment]
> Yes, please. I'm not touching this PR until it's green :-)

OK, I am changing it on my side then.

**Comment by zoltan-fedor** [comment]
Done. Sorry, it took me a while to realize that the tests were now in an inconsistent state - they were expecting multiple (conflicting) order of modules, so there was no way of fixing it without fixing the tests first, so all expects the same order of modules.

**Comment by etiennedi** [comment]
> If you prefer I could make a new PR with only one commit instead of this list of commits. Let me know.

No worries, I can just squash-merge them.

Thank you very much! Going to merge and release today.

**Pull request merged**
